[package]
name = "grabber"
version = "0.1.0"
authors = [
  "reynn <224374+reynn@users.noreply.github.com>"
]
edition = "2018"

[dependencies]
rawr = { git = "https://github.com/reynn/rawr", branch = "master" }
clap = { git = "https://github.com/clap-rs/clap/" }
reqwest = { version = "*", features = ["blocking"] }
chrono = "0.4.11"
toml = "0.5"
serde_derive = "1.0.106"
serde = "1.0.106"
